# -*- coding: utf-8 -*-
"""Airbnb Imoveis Nova York.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15cvdEiU9Q510jyVUekuyCaDXE7WWpQAm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('/content/AB_NYC_2019.csv')

data.info()

data.head()

"""## Calcular a média de todos os valores de aluguel da cidade de Nova York"""

preco_aluguel = data.loc[:, 'price']

np.mean(preco_aluguel)

"""## Contar todos os nomes distintos que aparecem na coluna região"""

regiao = data.loc[:, 'neighbourhood_group']

pd.unique(regiao)

"""## Encontrar o valor máximo da coluna que contém os valores dos aluguéis"""

preco_aluguel = data.loc[:, 'price']

np.max(preco_aluguel)

"""## Contar todos os nomes distintos que aparecem na coluna “room_type”?

"""

room_type = data.loc[:, 'room_type']
np.unique( room_type)